// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg54NA62nfwxHZ5E2mgCTFK_4w3zqM_QE',
    appId: '1:66189051073:web:04e6263bc227ccd1120040',
    messagingSenderId: '66189051073',
    projectId: 'pokhara-university-47f13',
    authDomain: 'pokhara-university-47f13.firebaseapp.com',
    databaseURL: 'https://pokhara-university-47f13-default-rtdb.firebaseio.com',
    storageBucket: 'pokhara-university-47f13.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATPNVUgfm8EL47eK0moTFoLjBgrV_P1xE',
    appId: '1:66189051073:android:8b4578dbf1561371120040',
    messagingSenderId: '66189051073',
    projectId: 'pokhara-university-47f13',
    databaseURL: 'https://pokhara-university-47f13-default-rtdb.firebaseio.com',
    storageBucket: 'pokhara-university-47f13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdAWNOyTqanS_tlCbqWFavs0FGwLEJloE',
    appId: '1:66189051073:ios:2a8afedec23d80f0120040',
    messagingSenderId: '66189051073',
    projectId: 'pokhara-university-47f13',
    databaseURL: 'https://pokhara-university-47f13-default-rtdb.firebaseio.com',
    storageBucket: 'pokhara-university-47f13.firebasestorage.app',
    iosBundleId: 'com.example.pokharaUniversityNewSyllabus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdAWNOyTqanS_tlCbqWFavs0FGwLEJloE',
    appId: '1:66189051073:ios:2a8afedec23d80f0120040',
    messagingSenderId: '66189051073',
    projectId: 'pokhara-university-47f13',
    databaseURL: 'https://pokhara-university-47f13-default-rtdb.firebaseio.com',
    storageBucket: 'pokhara-university-47f13.firebasestorage.app',
    iosBundleId: 'com.example.pokharaUniversityNewSyllabus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg54NA62nfwxHZ5E2mgCTFK_4w3zqM_QE',
    appId: '1:66189051073:web:b7012f2c7a1769f2120040',
    messagingSenderId: '66189051073',
    projectId: 'pokhara-university-47f13',
    authDomain: 'pokhara-university-47f13.firebaseapp.com',
    databaseURL: 'https://pokhara-university-47f13-default-rtdb.firebaseio.com',
    storageBucket: 'pokhara-university-47f13.firebasestorage.app',
  );
}
